In [1]:
import numpy as np
import cv2

In [3]:
arr = np.arange(0,10,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(np.full((3,3), fill_value=True, dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
arr = np.arange(0,10)
print(arr%2 ==1)
arr[arr%2 ==1]

[False  True False  True False  True False  True False  True]


array([1, 3, 5, 7, 9])

In [12]:
arr = np.arange(0,10)
print(arr%2 ==1)
arr[arr%2 ==1] =-1
print(arr)

[False  True False  True False  True False  True False  True]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# Exercise 2 (12-14)

In [2]:
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
img = mpimg.imread ("dog.jpeg")      
#plt.imshow(img)         

print(img.shape)

(534, 800, 3)


In [21]:
def lightness(img):

    channel_r = img[:,:,0]
    channel_g = img[:,:,1]
    channel_b = img[:,:,2]

    gray_value = (np.maximum(channel_r, np.maximum(channel_g, channel_b)) + np.minimum(channel_r, + np.minimum(channel_g, channel_b))) /2
    return gray_value

def avaerage(img):

    channel_r = img[:,:,0]
    channel_g = img[:,:,1]
    channel_b = img[:,:,2]

    gray_value = channel_r /3 + channel_g/3 + channel_b/3
    return gray_value

def luminority(img):

    channel_r = img[:,:,0]
    channel_g = img[:,:,1]
    channel_b = img[:,:,2]

    gray_value = channel_r * 0.21 + channel_g *  0.72 + channel_b* 0.07
    return gray_value

In [7]:
gray = (lightness(img))
cv2.imwrite("lightness.png", gray)
gray[0,0]

102.5

In [19]:
gray = (avaerage(img))
cv2.imwrite("avaerage.png", gray)
gray[0,0]

107.66666666666667

In [24]:
gray = (luminority(img))
cv2.imwrite("luminority.png", gray)
gray[0,0]

126.22999999999999

# Exercise 3 (15-21)

In [31]:
import pandas as pd
df = pd . read_csv ('advertising.csv ')

data = df.to_numpy ()
print(df.head())

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9


#### Câu hỏi 15: Lấy giá trị lớn nhất và chỉ mục tương ứng của nó trên cột Sales:

In [39]:
max_sales_value = np.max(data[:,3], axis=0)
print(max_sales_value)
index = np.argmax(data[:,3])
print(index)

27.0
175


#### Câu hỏi 16: Giá trị trung bình của cột TV là:

In [42]:
avaerage_tv = np.average(data[:,0], axis=0)
print(avaerage_tv)

147.0425


#### Câu hỏi 17: Số lượng bản ghi có giá trị tại cột Sales lớn hơn hoặc bằng 20 là:

In [46]:
data_sales = data[:,3]
#index = np.where((data_sales >= 20))
print(np.sum(data_sales >=20))

40


#### Câu hỏi 18: Tính giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng trên cột Sales lớn hơn hoặc bằng 15:

In [47]:
data_sales = data[:,3]
index = np.where((data_sales >= 15))

data_radio_condition  =  data[:,1][index]
print(np.average(data_radio_condition))

26.22293577981651


#### Câu hỏi 19: Tính tổng các hàng của cột Sales với điều kiện giá trị Newspaper lớn hơn giá trị trung bình của cột Newspaper:

In [49]:
average_newspaper = np.mean(data[:,2])
index = np.where((data[:,2] > average_newspaper))

sum_sales_condition = np.sum(data[:,3][index])
print(sum_sales_condition)

1405.1


#### Câu hỏi 20: Gọi giá trị trung bình của cột Sales là A. Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: nếu giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là Average. Sau đó in ra kết quả scores[7:10]

In [121]:
len(data)
average_sale = np.mean(data[:,3])
average_sale

15.130500000000001

In [112]:
average_sale = np.mean(data[:,3])

index = np.where((data[:,3] > average_sale))

reflection = np.zeros((200,1), dtype='U10')
print(data[:,3].shape)
reflection[np.where(data[:,3] > average_sale)] = "Good"
reflection[np.where(data[:,3] > average_sale)][7:10]

(200,)


array([['Good'],
       ['Good'],
       ['Good']], dtype='<U10')

In [110]:
reflection[np.where(data[:,3] > average_sale)] = "Good"
reflection[np.where(data[:,3] == average_sale)] = "Average"
reflection[np.where(data[:,3] < average_sale)] = "Bad"

print(reflection[7:10])

[['Bad']
 ['Bad']
 ['Good']]


#### Câu hỏi 21: Gọi giá trị trên cột Sales gần nhất với giá trị trung bình cũng chính cột Sales là A. Tạo ra mảng mới scores chứa các giá trị Good, Average và Bad sao cho: nếu giá trị hiện tại > A => giá trị trong mảng mới là Good, < A thì sẽ là Bad và = A sẽ là Average. Sau đó in ra kết quả scores[7:10]

In [130]:
mean_sale_value = np.mean(data[:,3])
print(f'mean: {mean_sale_value}')
distance_to_sales = np.absolute(np.diff(data[:,3] - mean_sale_value))
print(distance_to_sales)
index_min_distance  = np.argmin(distance_to_sales)
print(f'Index Minimum: {index_min_distance}')


mean: 15.130500000000001
[11.7  1.6  4.5  1.4 10.7  4.6  1.4  8.4 10.8  3.   4.8  8.2  4.5  5.3
  3.4  9.9 11.9 13.1  3.3  3.4  0.5 11.9 14.9 10.8  7.3  2.   5.9  2.
  8.4 10.9  9.5  1.3  4.2  5.5  5.9  7.6 10.7  4.6 11.4  4.9  0.5  3.6
  2.8  9.4  7.6  5.5 12.6  3.4 10.1  6.7  5.7 11.9  1.4  1.   3.5 18.2
  7.7 10.6  5.4 10.3 16.1  3.5  6.7  2.   4.7  0.3  2.4  5.5  3.4  4.
  5.9  3.6  2.2  6.   8.3  1.8  7.3  8.9  5.7  0.8  5.5  6.   2.3  8.1
  1.5  8.2  4.   3.1  3.8  2.7  6.7 12.1  2.8 10.7  5.4  0.2  3.8  4.9
  8.2  0.5  7.1  4.   0.1  1.   5.7  7.8  4.8  6.7 14.5  1.4  3.4  4.7
  3.8  6.3  2.   0.4  2.8  6.5  9.3  8.9  8.5  9.6  1.4  4.5  9.1  4.
  5.3 12.8 15.   8.1 16.1 12.  13.9  8.8  0.8  2.1 11.3 11.2 11.1  9.8
  8.3  0.9  9.7  1.9  2.   7.9  7.2 14.5  0.8  6.   4.5  5.   0.6  4.6
 17.4 12.1  5.2  2.8  5.6  3.5  3.1  6.6  1.9  6.1  5.   8.9  9.2  0.1
  2.9 11.6  9.1  9.9  9.1  0.2 10.5  6.8  3.5  0.1  0.8  2.1  1.7  8.5
 17.5  8.6  5.  12.3  7.   3.6 14.2  4.1  1.1  6.  13.7

In [ ]:
value = data[:,3][index_min_distance]

print(value)
print(f'Value closest sales value')